version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    ports:
      - "14069:8069"
      - "14072:8072"
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "en_US"
    volumes:
      - ./odoo/custom:/opt/odoo/custom:rw,z
      - ./odoo/auto:/opt/odoo/auto:rw,z
      - /opt/odoo/custom/src/odoo
    depends_on:
      - db
    networks:
      default:
    labels:
      doodba.domain.main: ""

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    environment:
      # Can connect database for any IP (No need ssl)
      WAN_CONNECTION: host
      WAN_AUTH_METHOD: md5
    restart: unless-stopped
    ports:
      - "5432:5432"

networks:
  default:
    driver_opts:
      encrypted: 1

volumes:
  filestore:
  db:
