name: pre-commit

on:
  push:
    branches:
      - 14.0
  pull_request:
    branches:
      - 14.0

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
